python plot_scripts/python_plots.py
python plot_scripts/python_plots_fatalities.py
python plot_scripts/python_plots_hospitalisation.py
python plot_scripts/python_plots_regional.py
Rscript plot_scripts/plots_provincial.R